code/examples/item-edit-modal.md
en/code/examples/item-edit-modal.md

안녕하세요. 오타를 발견해서 수정했어요!
잘 배우고 있습니다..! 🙇‍♂️

chore: 오타 수정

---

.vitepress/shared.mts

Since there are only title and description in the meta data, 
Kakaotalk does not render description on the sharing card.
Push meta data from pageData

feat: Update OG title and description from pagedata

---

.vitepress/shared.mts

Since we don't give title, description with frontmatter format in our document, 
The og title, descriptions need to be updated from page title, description.

feat: Update default og title, description

---

en/code/examples/code-directory.md
en/code/examples/login-start-page.md
en/code/examples/use-bottom-sheet.md

좋은 저장소를 공유해주셔서 감사합니다 🙏
영어 문서인데 아직 한글로 작성된 내용이 있어 수정 작업을 진행했습니다. (혹시 의도된 부분일까요..!? 😅)
추가적으로 공백 부분에서도 띄어쓰기 3칸으로 작성된 일부 코드들이 있어 함께 수정 작업에 포함됐습니다. (prettier 적용)
한번 검토해주시면 감사드립니다!

fix: Fix code written in Korean in English documentation

---

code/examples/use-page-state-coupling.md

언어가 한국어로 설정되어 있는데 영문으로 본문이 작성되어 있어 수정했어요.
영어를 다시 한국어로 바꾸는 과정이라 원문과 다를 수 있을거 같아 자세히 봐주시면 감사하겠습니다 🙇

fix: 'use-page-state-coupling' content to korean

---

code/examples/use-user.md
en/code/examples/use-user.md

안녕하세요, 좋은 저장소를 공유해주셔서 감사합니다 :)
예시 코드를 주석에 맞게 수정했습니다!

fix: wrong code example at checkIsValid

---

code/index.md

- `Anchor text`: "같이 실행되지 않는 코드 분리하기"
- `Link page title`: "동시에 실행되지 않는 코드 분리하기"

fix: Modify the anchor text to be the same as the title of the link page

---

.vitepress/en.mts
.vitepress/ko.mts
en/index.md
index.md

Fixed an issue where links in the sidebar and footer navigation were missing trailing slashes, causing page mapping errors.
<div>
<div/>

fix: Add trailing slashes to navigation links

---

code/examples/condition-name.md
en/code/examples/condition-name.md

In the initial example, the `price` object’s `value` property was used for comparison, but in the subsequent example, the comparison was made directly on the `price` object.
I think this is unintended behavior, So I fixed it by ensuring the comparison uses the `value` property consistently in both examples.

fix: Fix condition-name typo

---

.vitepress/theme/Layout.vue

| Before                                                                                         | After                                                                                       |
|------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| ![before](https://github.com/user-attachments/assets/52bea77b-39f4-46ad-a9f7-47665bde2497)     | ![after](https://github.com/user-attachments/assets/9cbdb9df-da21-4afa-856e-09fba8bd5d52)   |
- 구성요소(컴포넌트) 높이에 따라 스크롤바가 생기거나 사라져, 레이아웃이 좌우로 흔들리는 문제가 있었습니다.
- `overflow-y: scroll;` (혹은 `scrollbar-gutter: stable;`) 설정으로 **항상 스크롤바 공간을 확보**하여 문제를 해결했습니다.
- 짧은 문서(높이가 낮은)에서는 스크롤바가 없어서 레이아웃이 살짝 오른쪽으로 이동하는 “레이아웃 쉬프팅”이 …

fix: resolve layout shifting caused by component height differences

---

code/examples/user-policy.md
en/code/examples/user-policy.md

- Standardize button text and permission properties across all examples
- Align code implementations with the original requirements
- Fix property naming to ensure consistent behavior
Before: Mixed use of "Read"/"View" buttons and "canRead"/"canView" properties
After: Consistent use of "View" buttons and "canView" properties throughout examples

Fix: Inconsistencies in user policy code examples

---

code/examples/login-start-page.md
en/code/examples/login-start-page.md

- Fix undefined data.name reference in InviteButton component
- Use name prop directly from component props
The InviteButton component was trying to access data.name which doesn't exist in its scope, causing potential runtime errors.

Fix: Correct undefined data reference in InviteButton component

---

.vitepress/en.mts

- Update the "Home" button in the nav bar.
- Redirect to the Korean homepage (/) instead of the English homepage (/en) in English mode.

fix: update incorrect home redirection in en mode

---

code/examples/item-edit-modal.md
en/code/examples/item-edit-modal.md

- update code highlight in `item-edit-modal`
- comparing the codeblock before and after #56 was committed.
URLs:
- https://frontend-fundamentals.com/code/examples/item-edit-modal.html#%F0%9F%93%9D-%E1%84%8F%E1%85%A9%E1%84%83%E1%85%B3-%E1%84%8B%E1%85%A8%E1%84%89%E1%85%B5
- https://frontend-fundamentals.com/en/code/examples/item-edit-modal.html#%F0%9F%93%9D-code-example
Before:
After:

docs: update wrong codeblock highlight

---

.vitepress/ja.mts

- fix community link in ja docs sidebar `/code/community` -> `/ja/code/community`

fix: fix community link in ja docs sidebar

---

.vitepress/theme/components/Comments.vue

Currently, the Giscus theme script is set to `data-theme="preferred_color_scheme"`, which reflects the user's preferred theme.
However, there is an issue where the Giscus theme does not change when the theme toggle button is clicked.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="center">
Device Preferred: <code>Dark</code> / Page: <code>Dark</code>
</td>
<td align="center">
Device Preferred: <code>Dark</code> / Page: <code>Light</code>
</td>
</tr>
</table>
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="center">
Device Preferred: <code>Dark</code> / Page: <code>Dark</code>
</td>
<td align="center">
Device Preferred: <code>Dark</code> / Page: <code>Light</code>
</td>
</tr>
</table>

fix: update giscus theme to change dynamically based on page theme

---

ja/code/examples/item-edit-modal.md

I added the Japanese content that was missing in the changes from PR #119 
**URL**
https://frontend-fundamentals.com/ja/code/examples/item-edit-modal.html
**Before:**
**After:**

docs: update wrong codeblock highlight in Japanese

---

.vitepress/ja.mts
.vitepress/shared.mts
ja/code/examples/user-policy.md

Improve Japanese locale support and configuration:
- Fix incorrectly configured Japanese locale in VitePress search (was being ignored)
**Before/After screenshots:**
- Remove duplicate head configurations from ja.mts (now using shared config)
(reason: https://github.com/toss/frontend-fundamentals/pull/49)
- Fix permission naming consistency (canView → canRead)

Fix: Add Japanese locale and remove duplicate configurations

---

.vitepress/theme/components/Comments.vue
.vitepress/theme/hooks/useGiscusTheme.tsx
.vitepress/theme/utils/index.ts

- Fix UI clarity by updating Giscus theme to tritanopia
- Add dynamic language support for comment section
- Ensure dark/light mode is properly applied after giscus iframe is fully loaded
- noborder theme (Before) vs tritanopia theme (After)
- Please review both themes and let me know your preference:
- Dynamic language switching based on user preferences
- Maintain theme consistency by applying giscus theme after load

Feat: Improve Giscus theme visibility and add i18n support

---

.vitepress/shared.mts
.vitepress/theme/custom.css

- Added Toss Product Sans font integration
Screenshot taken on Windows screen to clearly show font differences
|<img width="1055" alt="before" src="https://github.com/user-attachments/assets/062de609-f7d3-43b4-866b-830d55c62f41" />|<img width="1055" alt="after" src="https://github.com/user-attachments/assets/c85233b8-9fc5-4ee0-929c-80a1f853ceb2" />|
|:---:|:---:|

Feat: Applied Toss Product Sans font

---

code/examples/item-edit-modal.md
en/code/examples/item-edit-modal.md
ja/code/examples/item-edit-modal.md

Through [this discussion](https://github.com/toss/frontend-fundamentals/discussions/77#discussioncomment-11898705), i improve the explanation of props drilling by adding context about abstraction removal.
When related documents are created in the future, i hope they will be linked here.
- Add context about abstraction removal in item-edit-modal.md, /ja/item-edit-modal.md, /en/item-edti-modal.md

docs: improve item-edit-modal.md by adding abstraction concepts (#77)

---

en/code/examples/item-edit-modal.md
en/code/examples/use-user.md

- Complete unfinished sentence in `use-user.md`
- Change Korean `닫기` to `Close` in `item-edit-modal.md`
Simple text corrections in English documentation files. No visual changes.

Fix: Correct typos in English documentation

---

en/code/examples/condition-name.md
en/code/examples/submit-button.md

- Revised grammar considering natural flow `submit-button.md`
- Replaced the Yes24 link with an Amazon link for localization, as Yes24 is not commonly used in English-speaking countries and Amazon is a widely recognized online bookstore. `condition-name.md`
Simple text corrections in English documentation files. No visual changes.

Fix: Improve grammar and localize link

---

en/code/examples/condition-name.md

- Since the link still redirects to Yes24 instead of applying #140, the correct Amazon link has been updated to redirect properly in `condition-name.md`
Simple text corrections in English documentation files. No visual changes.

Fix: Correct localized link 

---

ch/code/examples/code-directory.md
ch/code/examples/http.md
code/examples/code-directory.md
code/examples/form-fields.md
code/examples/http.md
en/code/examples/code-directory.md
en/code/examples/http.md
ja/code/examples/code-directory.md
ja/code/examples/http.md

Fixes three syntax issues:
- Adds missing period in email validation message - https://github.com/toss/frontend-fundamentals/commit/c4bda53e6fb7239135f469d6bcbfef0ae7a68408
- Adds missing 'from' keyword in import statement - https://github.com/toss/frontend-fundamentals/commit/db0a8700fa99721ec2eaca1804aa9f3d7315d5eb
- Changes requiring discussion:
- [이름 겹치지 않게 관리하기](https://frontend-fundamentals.com/code/examples/http.html)
- For consistency between `Code Example` and `Work on Improving` sections, I added Auth Token to `Code Example`. Based on the document context, I believe adding Auth Token was appropriate - could you confirm if this assessment is correct? - https://github.com/toss/frontend-fundamentals/commit/69a4ab221cb6523c579351e336b6aa8864faade6
Simple text corrections in …

Fix: Add missing syntax and normalize Auth Token usage

---

.vitepress/theme/index.ts

- Added DefaultTheme import from vitepress/theme
- Extended DefaultTheme in configuration to inherit base components
- Fixed by following the solution from [vuejs/vitepress#1576](https://github.com/vuejs/vitepress/issues/1576)
The Badge component in VitePress is part of the DefaultTheme package. Initially, we couldn't access it because we tried implementing a custom theme without importing DefaultTheme.
Finally, the badge is visible!
|<img width="1457" alt="before" src="https://github.com/user-attachments/assets/584eaa1b-8b0a-4272-91d3-dbba5ab670b5" />|<img width="1457" alt="after" src="https://github.com/user-attachments/assets/36ac2709-1e9c-4e06-aab9-db748dc70595" />|
|:---:|:---:|

Fix: Badge Component Not Rendering

---

fundamentals/code-quality/.vitepress/config.mts

- Revise the Giscus index to use document titles instead of path names
- Change Path Example 1
- Change Path Example 2

Revise the Giscus index to use document titles instead of path names

---

README.md

- 기존 이미지 경로인 ./public/images/ff-meta.png는 GitHub에서 렌더링되지 않아 ./images/ff-meta.png로 수정했습니다.
English
- The original path ./public/images/ff-meta.png did not render on GitHub, so it was changed to ./images/ff-meta.png.
**Before**
**After**

fix broken image path in README.md

---

fundamentals/bundling/webpack-tutorial/react.md

- 누락된 마침표를 추가하고 띄어쓰기를 수정했습니다.
> 본용언이 합성어나 파생어일 때 뒤의 보조용언은 띄어 쓰는 것이 원칙입니다. 한글맞춤법 제47항 해설에 따르면, 본용언의 활용형이 2음절 이내면 붙여 쓰는 것도 허용되나, 현실 언어생활을 볼 때 이 규정을 모두 적용하기는 쉽지 않습니다. 따라서 '나가다'와 '버리다'가 보조용언으로 쓰일 때만 이 해설 규정을 적용했습니다.
> 
> 예) 먹어나가다(ㅇ)/ 먹어 나가다(ㅇ)
> 공부해나가다(x) -> 공부해 나가다(ㅇ)
> 
> 나와버리다(ㅇ)/ 나와 버리다(ㅇ) 해치워버리다(x) -> 해치워 버리다(ㅇ)
- 누락된 설정 변경을 추가했습니다.
- [HTML을 React 컴포넌트로 변환하기](https://frontend-fundamentals.com/bundling/webpack-tutorial/react.html#_4-html%E1%84%8B%E1%85%B3%E1%86%AF-react-%E1%84%8F%E1%85%A5%E1%86%B7%E1%84%91%E1%85%A9%E1%84%82%E1%85%A5%E1%86%AB%E1%84%90%E1%85%B3%E1%84%85%E1%85%A9-%E1%84%87%E1%85%A7%E1%86%AB%E1%84%92%E1%85%AA%E1%86%AB%E1%84%92%E1%85%A1%E1%84%80%E1%85%B5)에서 `main.ts` 파일 이름을 `main.tsx`로 변경함에 따라, 기존 웹팩 설정 `entry`를 변경합니다.
| | |
|:—:|:—:|

docs: fix format and spacing

---

fundamentals/bundling/.vitepress/config.mts
fundamentals/bundling/.vitepress/shared.mts

- 문제
- Windows 11 Chrome 137.0.7151.56 버전에서 번들링 콘텐츠의 폰트가 custom.css에 정의된 Toss Product Sans 폰트로 
로드되지 않는 문제 발생
- 원인
- `fundamentals/bundling/.vitepress/config.mts`의 head 태그가 `fundamentals/bundling/.vitepress/shared.mts`의 head 태그와 중복되어 폰트 적용이 제대로 안되는 문제가 발생
- 해결 방법 및 수정사항
- `fundamentals/bundling/.vitepress/config.mts`의 head 태그 제거 후 공통 설정은 `shared.mts`에서 관리하도록 일원화
- `fundamentals/bundling/.vitepress/shared.mts`의 head 섹션에 Toss Product Sans 폰트를 적용하기 위한 스타일시트 추가
- Favicon 설정 정리
- 기존 기본 favicon (`{ rel: "icon", type: "image/x-icon", href: "/images/favicon.ico" }`) 삭제
- 번들링 전용 favicon (`{ rel: "icon", type: "image/x-icon", href: "/bundling/images/favicon.ico" }`)만 유지 
- `code-quality`와 변수명을 동일시 하기 위해 `sharedConfig` -> `shared` 로 변수명 변경
- 개인 의견: 그러나 sharedConfig라는 변수명이 더 직관적인 것 같아 shared 대신 …

fix: Windows 11 Chrome에서 Toss Product Sans 폰트 미적용 문제 해결

---

fundamentals/code-quality/code/examples/item-edit-modal.md

This PR fixes a bug in the `item-edit-modal.md` example where the `ItemEditBody` component was trying to use `keyword` state and `onKeywordChange` function without receiving them as props. 
**Problem resolved:**
- `ItemEditBody` component was missing required props (`keyword`, `onKeywordChange`)
- Example code was not runnable due to undefined variable references
- Props drilling pattern was incomplete, making the example confusing for learners
**Solution applied:**
- Added missing `keyword` and `onKeywordChange` props to `ItemEditBody`
- Updated component function signature to accept the required props
- Maintained existing component structure while fixing the prop flow
```tsx
//before
function ItemEditModal({ open, items, recommendedItems, onConfirm, onClose }) {
const [keyword, …
```

docs: add missing props to ItemEditBody component

---

fundamentals/code-quality/code/examples/item-edit-modal.md
fundamentals/code-quality/ja/code/examples/item-edit-modal.md

- **Corrected style prop usage**:
Updated inline style from `style="display: flex; justify-content: space-between;"` to `style={{ display: "flex", justifyContent: "space-between" }}` for valid JSX and consistency.
- **Added missing keyword prop**:
Passed the required `keyword` prop to `ItemEditBody` for controlled input, ensuring correct state management and preventing uncontrolled behavior.
- **Fixed `ItemEditList` props and example comment**:
Adjusted props for `ItemEditList` to match the component's usage, removing unrelated props from `ItemEditBody`.
This change applies to Korean and Japanese documents.
Since ItemEditList is an example that shows how to use the Context API, the rendering logic is simply written in comments, but if you need the exact code, please let me know!
| Before …

docs: fix correct style prop usage and prop passing in ItemEditModal composition example

---

fundamentals/code-quality/code/examples/submit-button.md
fundamentals/code-quality/en/code/examples/submit-button.md
fundamentals/code-quality/ja/code/examples/submit-button.md
fundamentals/code-quality/zh-hans/code/examples/submit-button.md

This PR improves the SubmitButton example in the documentation by unifying the animation function name from `showAnimation` to `showButtonAnimation` across all related components.
In the original example, the animation is played using the `showButtonAnimation()` function:
```tsx
function SubmitButton() {
const isViewer = useRole() === "viewer";
useEffect(() => {
if (isViewer) {
return;
}
showButtonAnimation();
}, [isViewer]);
return isViewer ? (
<TextButton disabled>Submit</TextButton>
) : (
<Button type="submit">Submit</Button>
);
}
```
However, in the improved example, the animation function is called `showAnimation()`, which introduces inconsistency in function naming and reduces code readability.
Different function names may confuse readers into thinking these are different behaviors, …

docs: Unify animation function name in SubmitButton example to improve code clarity

---

fundamentals/today-i-learned/src/components/features/auth/UnauthenticatedState.tsx
fundamentals/today-i-learned/src/components/features/discussions/PostCard.tsx
fundamentals/today-i-learned/src/components/features/discussions/WeeklyTop5.tsx
fundamentals/today-i-learned/src/components/shared/ShareLinkButton.tsx
fundamentals/today-i-learned/src/components/shared/layout/Layout.tsx
fundamentals/today-i-learned/src/components/shared/ui/InteractionButtons.tsx
fundamentals/today-i-learned/src/pages/post/PostDetailPage.tsx
fundamentals/today-i-learned/src/pages/timeline/TimelinePage.tsx

- #450 
- 게시글 피드, 상세 페이지에서 컨텐츠와 TOP5의 영역을 full screen으로 적용하였습니다.
- 나누어진 각 영역에서 스크롤이 자연스럽게 작동되도록 사용성을 개선하였습니다.
- 변경된 layout에 따른 mobile 대응을 진행하였습니다.
- 비로그인 상태 영역 문구를 변경하고 가운데 정렬로 수정하였습니다.
- 피드 페이지의 PostCard의 style을 figma에 맞게 수정하였습니다.
| **Before** | **After** |
| ---------- | --------- |
| <img width="2032" height="1161" alt="스크린샷 2025-09-29 03 18 31" src="https://github.com/user-attachments/assets/2c9b7771-3ee7-46a1-a6a9-4915615307cd" /> | <img width="2032" height="1161" alt="스크린샷 2025-09-29 03 18 35" src="https://github.com/user-attachments/assets/56dfef6e-1824-4fd0-94d7-8110644ee3f0" /> 
| <video src="https://github.com/user-attachments/assets/364cca31-083a-4e02-ab7e-ff79d23cab7f" /> | <video src="https://github.com/user-attachments/assets/e01902a4-db34-4631-bd3d-8005a7a6393d" …

TIL > refactor: 피드 컨텐츠와 주간 TOP5 layout 사용성 개선
