toss/frontend-fundamentals

- code/examples/login-start-page.md
- en/code/examples/login-start-page.md
안녕하세요,
예시 코드가 잘못되어 있는 부분을 발견해 수정했어요!
> fix: wrong code example at login start page

- code/examples/ternary-operator.md
- en/code/examples/ternary-operator.md
https://github.com/toss/frontend-fundamentals/pull/38
There was some code that wasn't removed in this PR.
> remove unnecessary code

- code/examples/condition-name.md
- en/code/examples/condition-name.md
This pull request fixes typo in example code (`cagetory` → `category`)
> fix: fix typo

- .vitepress/ko.mts
단어를 변경하여 문맥을 개선하고 통일성을 높였어요.
카테고리 제목과 내용의 제목이 통일되지 않아 어색함이 느껴져서, `같이`를 `함께`로 변경하여 통일성을 높였어요 !
> fix: Match titles to improve consistency

- .vitepress/ko.mts
- code/examples/submit-button.md
메뉴 제목과 상세 제목이 일치하지 않아 수정PR 올립니다!
> fix:  menu title

- code/examples/user-policy.md
- en/code/examples/user-policy.md
I removed what seemed to be an unnecessary deps array :)
> fix: fix user-policy typo

- code/examples/condition-name.md
- code/examples/ternary-operator.md
- code/examples/user-policy.md
- code/index.md
카테고리명과 실제 문서명이 맞지 않는 문서들을 통일합니다.
> fix: 카테고리명과 실제 문서 제목 통일

- code/examples/use-user.md
- en/code/examples/use-user.md
Fix typo by replacing semicolon with comma and improve readability by replacing arrow function with direct function reference.
> Fix: fix use user typo

- .vitepress/en.mts
- .vitepress/ko.mts
- Fix incorrect sidebar structure in English documentation
- Use encoded URLs
> fix: update incorrect sidebar items

- code/community.md
- en/code/community.md
- URL encoding
- Fix missing spaces in Korean documentation
- Add missing translations in English documentation
> docs: update `community.md`

- code/examples/use-user.md
- code/examples/user-policy.md
- en/code/examples/use-user.md
- en/code/examples/user-policy.md
- Remove trailing commas from code blocks in docs
> Fix: delete unnecessary commas

- .github/DISCUSSION_TEMPLATE/pull_request_template.md
> feat: PR template을 추가합니다

- code/examples/use-page-state-readability.md
- Add missed import statements in `use-page-state-readability.md`
> Docs: add missed import statements

- code/examples/use-user.md
- en/code/examples/use-user.md
- Added tip section about Discriminated Union type for validation functions
- Add example demonstrating type-safe validation checks
- Three highlighted lines show TypeScript's Discriminated Union and type narrowing behavior.
- Add explanations in both [Korean](https://github.com/KNHui/frontend-fundamentals/blob/90858f9e39bd94fc2149442362928318d6a3d814/code/examples/use-user.md?plain=1#L182-L210) and [English](https://github.com/KNHui/frontend-fundamentals/blob/90858f9e39bd94fc2149442362928318d6a3d814/en/code/examples/use-user.md?plain=1#L182-L210)
- Changes requiring discussion:
- #108 
| ![image](https://github.com/user-attachments/assets/b04e945c-46fc-4c8e-9c9f-9c0ce3f093df) | ![image](https://github.com/user-attachments/assets/e42cd200-165b-469b-a829-6ea467cbddd8) |
|:--:|:--:| …
> docs: Add tip for Discriminated Union type to use-user.md

- .github/DISCUSSION_TEMPLATE/suggest-new-strategy.yml
> fix: Fix duplicate id in  'DISCUSSION_TEMPLATE/suggest-new-strategy.yml'

- .vitepress/theme/components/GithubDiscussions.vue
- .vitepress/theme/components/GithubDiscussionsDetail.vue
- .vitepress/theme/composables/useGithubApi.ts
- .vitepress/theme/composables/useGithubDiscussions.ts
- .vitepress/theme/index.ts
- .vitepress/theme/utils/markdown.ts
- code/dicussions/detail.md
Add the discussion detail page.
- The markdown converter and API call functionality will be replaced with a library later.
> feat: Add Discussion Detail Page

- .vitepress/theme/components/GithubDiscussions.vue
- .vitepress/theme/composables/useDiscussionFilter.ts
> feat: Add "인기글" Category

- .vitepress/theme/components/GithubDiscussions.vue
> feat: Add Write Button

- .vitepress/theme/components/GithubDiscussions.vue
> fix: 클릭 핸들러를 추가합니다

- fundamentals/code-quality/code/examples/http.md
- fundamentals/code-quality/ja/code/examples/http.md
- fundamentals/code-quality/zh-hans/code/examples/http.md
안녕하세요! [문서](https://frontend-fundamentals.com/code/examples/http.html#%E2%9C%8F%EF%B8%8F-%E1%84%80%E1%85%A2%E1%84%89%E1%85%A5%E1%86%AB%E1%84%92%E1%85%A2%E1%84%87%E1%85%A9%E1%84%80%E1%85%B5)를 읽으면서 오타를 발견해서 수정해봤어요.
감사합니다..! 🙇‍♂️
| | |
|:—:|:—:|
> docs: fix typo in http

- fundamentals/bundling/.vitepress/config.ts
1차 리팩토링입니다.
이 틀을 기본으로, @Kimbangg 님이 컨텐츠를 보강하는 2차 리팩토링을 하고,
최종 폴더구조 확정 및 윤문하는 3차 리팩토링을 진행할 예정입니다.
| | |
|:—:|:—:|
> refactor: (Bundling fundamentals) folder structure 1st reframing

- fundamentals/bundling/.vitepress/config.mts
- fundamentals/bundling/reference/dev/hmr.md
- fundamentals/bundling/reference/dev/source-map.md
- fundamentals/bundling/tutorial/with-react.md
- vercel.json
> deploy bundling fundamentals

- .pnp.cjs
- fundamentals/bundling/.vitepress/config.mts
- fundamentals/code-quality/.vitepress/config.mts
- fundamentals/code-quality/.vitepress/theme/config/OneNavigationItems.ts
- package.json
- vercel.json
- yarn.lock
> migate vercel deploy ci

- fundamentals/bundling/.vitepress/config.mts
> refactor: table of contents of bundling fundamentals tutorial

- fundamentals/bundling/.vitepress/config.mts
- fundamentals/bundling/.vitepress/shared.mts
> feat: add search feature

- fundamentals/code-quality/.vitepress/shared.mts
> fix: add favicon

- fundamentals/code-quality/code/community/good-discussions.md
> fix: update broken link

- fundamentals/bundling/.vitepress/config.mts
- Remove Unused Cateogory
| | |
|:—:|:—:|
> feat: remove unused category

- fundamentals/bundling/.vitepress/shared.mts
> feat: 번들링 컨텐츠 x에 업로드시 og 보이도록 수정

- fundamentals/bundling/.vitepress/config.mts
config.mts에 다시 넣어줍니다!
| | |
|:—:|:—:|
> fix: shared만 넣어서, 적용안되는 것 수정

- fundamentals/bundling/deep-dive/optimization/tree-shaking.md
> fix: remove unnessary `\` 

- fundamentals/bundling/.vitepress/config.mts
- fundamentals/bundling/zh-hans/index.md
- 한국어 번들링 페이지 언어 변경 메뉴가 보이지 않는 현상 수정
- 한국어 번들링 페이지 툴팁이 영어로 나오는 현상 수정
- 한국어 번들링 페이지에서 코드퀄리티 페이지로 이동 시 영문 페이지로 이동되는 현상 수정
- 누락된 중국어 Coming Soon 페이지 추가
**English**
- Korean bundling page language change menu not visible
- Fixed tooltips on Korean bundling page appearing in English
- Fixed being navigate to the English page when navigating to the Code Quality page from the Korean bundling page
- Add the missing Chinese Coming Soon page
> fix : multilingual menu is not visible on bundling page

- fundamentals/a11y/.vitepress/config.mts
- fundamentals/a11y/en/index.md
- fundamentals/a11y/ja/index.md
- fundamentals/a11y/zh-hans/index.md
- fundamentals/shared/config/OneNavigationItems.ts
> fix: accessibility -> a11y

- api/github/login.js
> feat: Pass redirect uri to github oauth login

- .github/PULL_REQUEST_TEMPLATE.md
기본적으로 제공되는 PR template에 있는 표가 깨지고 있습니다. 
- 문제 원인
- `|:—:|:—:|`: 줄표(엔 대시)
- 해결 방안
- `|:-:|:-:|`: 붙임표(하이픈)
|:-:|:-:|
|<img width="379" height="175" alt="as-is-pr" src="https://github.com/user-attachments/assets/cb411bda-a00f-47fd-b714-f87f7597727f" /> | <img width="388" height="228" alt="to-be-pr" src="https://github.com/user-attachments/assets/377c0cd8-c3bb-414e-aa7b-4781e5cadcb3" />|
> docs: fix table formatting in pull request template

- fundamentals/code-quality/code/examples/magic-number-readability.md
> fix: correct typo in `magic-number-readability`

- vercel.json
- vercel rewrite 경로를 추가했어요. - related at [this discussion](https://community.vercel.com/t/react-router-and-vite-app-404-error-for-routes-on-vercel-deployment/2920)
> TIL > feat: vercel.json에 리다이렉트 추가

- fundamentals/a11y/principles.md
Add a missing link to the key principles of accessibility.
|:-:|:-:|
| | |
> docs: add missing links to key principles
